import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { Footer } from "../../share/components/Footer";
import { Navbar } from "../../share/components/Navbar";
import { UserAside } from "../../share/components/userAside";
import { useTranslation } from "react-i18next";
import { UserBasketCard } from "../../share/components/userBasketCard/intex";

const UserBasket: NextPage = () => {
  const { t } = useTranslation();

  return (
    <>
      <Head>
        <title>Foody | User Basket</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/mainBurger.svg" />
      </Head>

      <main>
        <Navbar isRegister={true} forAdmin={null} forLogin={null} />

        <section className="mx-0 sm:m-8 flex justify-center gap-10">
          <UserAside />
          <div className="w-full flex flex-col px-3 sm:px-8 py-10 flex-wrap gap-0 sm:bg-whiteLight1">
            <h2 className="font-semibold text-3xl text-grayText2">{t("userDesc2")}</h2>
            <UserBasketCard />
          </div>
        </section>

        <Footer isTop={false} />
      </main>
    </>
  );
};

export default UserBasket;
