import { NextPage } from "next";
import Head from "next/head";
import { Navbar } from "../../../share/components/Navbar";
import Image from "next/image";
import { Footer } from "../../../share/components/Footer";
import { RestDetailHeader } from "../../../share/components/restaurantDetailHeader";

const RestaurantDetail: NextPage = () => {
  return (
    <>
      <Head>
        <title>Foody | Restaurant Detail</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/mainBurger.svg" />
      </Head>

      <main>
        <Navbar isRegister={true} forAdmin={null} forLogin={null} />

        <section className="m-8 flex flex-col">
          <RestDetailHeader/>
          <section className="flex justify-between">
            <div></div>
          </section>
        </section>

        <Footer isTop={false} />
      </main>
    </>
  );
};

export default RestaurantDetail;
