import type { NextPage } from "next";
import Head from "next/head";
import { AdminAside } from "../../../share/components/adminAside";
import OrdersChart from "../../../share/components/ordersChart";
import Barchart from "../../../share/components/LineChart";
import { AdminLeftModal } from "../../../share/components/adminLeftModal";
import { useState } from "react";
import AdminCard from "../../../share/components/adminCard";
import AdminSecondTitle from "../../../share/components/adminSecondTitle";
import { Navbar } from "@/share/components/Navbar";

const AdminProducts: NextPage = () => {

  return (
    <>
      <Head>
        <title>admin</title>
        <meta name="Products" content="Generated by create next app" />
        <link rel="icon" href="/admin-icon.png" />
      </Head>

      <div className=" bg-textBlack min-h-screen px-4">
        <Navbar adminNavbar={true}/>


   
        <main className="flex">
          <div className=" hidden sm:block">
            <AdminAside />
          </div>

    

          <section className=" w-full">
            <div className="m-5">
              <AdminSecondTitle  name="Products " p1="Products"/>
            </div>

            <div className=" w-full sm:w-auto m-5 flex flex-wrap gap-10 justify-center">
              <AdminCard
                foodname={"Marqarita"}
                restoranname={"Papa John’s"}
                foodimage={"/adminMarqarita.svg"}
                foodprice={16}
              />{" "}

            </div>
          </section>
        </main>
      </div>
    </>
  );
};

export default AdminProducts;
