import type { NextPage } from "next";
import Head from "next/head";
import { AdminHeader } from "../../share/components/adminHeader";
import { AdminAside } from "../../share/components/adminAside";
import OrdersChart from "../../share/components/ordersChart";
import Barchart from "../../share/components/LineChart";
import { AdminLeftModal } from "../../share/components/adminLeftModal";
import { useState } from "react";
import AdminCard from "../../share/components/adminCard";

const AdminDashboard: NextPage = () => {
  const [isHiddenModal, setIsHiddenModal] = useState<boolean>(true);
  function changeHidden() {
    setIsHiddenModal((prev) => !prev);
    console.log(isHiddenModal);
  }
  return (
    <>
      <Head>
        <title>admin</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/admin-icon.png" />
      </Head>

      <div className=" bg-textBlack min-h-screen px-4">
        <AdminHeader onClickButton={changeHidden} />

        <AdminLeftModal onClickClose={changeHidden} hidden={isHiddenModal} />
        <main>
          <AdminAside />
          <div className=" gap-4   hidden">
            <OrdersChart />
            <Barchart />
          </div>
          <section>
            <AdminCard
              foodname={"Marqarita"}
              restoranname={"Papa John’s"}
              foodimage={"adminMarqarita.svg"}
              foodprice={16}
            />
          </section>
        </main>
      </div>
    </>
  );
};

export default AdminDashboard;
