import type { NextPage } from "next";
import Head from "next/head";
import { AdminAside } from "../../share/components/adminAside";
import OrdersChart from "../../share/components/ordersChart";
import Barchart from "../../share/components/LineChart";
import { AdminLeftModal } from "../../share/components/adminLeftModal";
import { useEffect, useState } from "react";
import { Navbar } from "@/share/components/Navbar";
import { useRouter } from "next/router";

const AdminDashboard: NextPage = () => {
  const [isHiddenModal, setIsHiddenModal] = useState<boolean>(true);
  function changeHidden() {
    setIsHiddenModal((prev) => !prev);
    console.log(isHiddenModal);
  }

  const router = useRouter();

  useEffect(() => {
    router.push("/admin/dashboard");
  }, []);
  
  return (
    <>
      <Head>
        <title>Admin</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/admin-icon.png" />
      </Head>

      <div className=" bg-textBlack min-h-screen px-4">
        <Navbar adminNavbar={true} />

        <AdminLeftModal onClickClose={changeHidden} hidden={isHiddenModal} />
        <main>
          <AdminAside />
          <div className=" gap-4   flex">
            <OrdersChart />
            <Barchart />
          </div>
        </main>
      </div>
    </>
  );
};

export default AdminDashboard;
