import Head from "next/head";
import Image from "next/image";
import React from "react";
import { Button } from "../../../share/components/Button";
import { Langugages } from "../../../share/components/Languages";
import { useTranslation } from "react-i18next";

export default function AdminLogin() {
  const { t, i18n } = useTranslation();
  return (
    <div className=" min-h-screen bg-darkBlue_1">
      <Head>
        <title>Foody | Admin</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/admin-icon.png" />
      </Head>
      <div>
        <header className="  mb-20  md:mb-44 pt-14  pl-8 ">
          <h1
            style={{ letterSpacing: "0.84px" }}
            className=" text-[#F5F5F5] font-extrabold text-[28px]  "
          >
            Foody{" "}
            <span
              style={{ letterSpacing: "0.84px" }}
              className=" text-[#EAAB00]"
            >
              .
            </span>{" "}
          </h1>
        </header>

        <main>
          <div className=" flex  justify-center pb-7 ">
          <div className=" flex flex-col-reverse   sm:flex-col-reverse  md:flex-row  ">
            <div className=" w-full sm:w-full md:w-1/2  md:bg-darkBlue_2 py-14  px-6 sm:px-7 md:px-12 ">
              <p className=" text-grayText font-bold text-4xl text-center  mb-10">
               {t("adminDesc")}
              </p>
              <div className=" flex flex-col  gap-6 mb-9">
                <input
              
                  className=" rounded bg-lightGray capitalize text-grayText py-4 pl-10 font-medium text-lg "
                  placeholder={t("username")}
                  type="text"
                />
                <input
              
                  className=" rounded   bg-lightGray capitalize text-grayText py-4 pl-10 font-medium text-lg "
                  placeholder={t("password")}
                  type="text"
                />
              </div>
                <Button innerText={ t("signIn")} className=" text-white font-medium text-2xl  w-full bg-lightPurple_3 py-3 rounded" />
            </div>
              <div className=" w-full sm:w-full relative md:w-1/2  py-14 px-7 md:bg-adminLogin">
                <div className=" absolute  top-2  right-3"><Langugages bgDark />
                </div>
              <div className="">
                <Image
                  className=" w-full"
                  src="/admin-login.svg"
                  width={0}
                  height={0}
                  alt=" admin-login"
                />
              </div>
            </div>
          </div>
          </div>
        </main>
      </div>
    </div>
  );
}
