import Barchart from "@/share/components/LineChart";
import { Navbar } from "@/share/components/Navbar";
import { AdminAside } from "@/share/components/adminAside";
import { AdminHeader } from "@/share/components/adminHeader";
import { AdminLeftModal } from "@/share/components/adminLeftModal";
import AdminOrdersTable from "@/share/components/adminOrdersTable";
import AdminSecondTitle from "@/share/components/adminSecondTitle";
import { getOrder } from "@/share/services/axios";
import { useGlobalStore } from "@/share/services/provider";
import Head from "next/head";
import React, { useEffect, useState } from "react";
import { useTranslation } from "react-i18next";
import { ToastContainer, toast } from "react-toastify";

// const item = [
//   {
//     id: 9177,
//     customerId: 22401,
//     Time: "25 Dec 2021",
//     Address: "29 Eve Street, 543 Evenue Road, Ny 87876",
//     Amount: "$249.7",
//     Payment: "Cash",
//     Contact: "994-51-410-3130",
//   },
//   {
//     id: 9178,
//     customerId: 22401,
//     Time: "25 Dec 2021",
//     Address: "29 Eve Street, 543 Evenue Road, Ny 87876",
//     Amount: "$249.7",
//     Payment: "Cash",
//     Contact: "994-51-410-3130",
//   },
//   {
//     id: 9179,
//     customerId: 22401,
//     Time: "25 Dec 2021",
//     Address: "29 Eve Street, 543 Evenue Road, Ny 87876",
//     Amount: "$249.7",
//     Payment: "Cash",
//     Contact: "994-51-410-3130",
//   },
//   {
//     id: 9200,
//     customerId: 22401,
//     Time: "25 Dec 2021",
//     Address: "29 Eve Street, 543 Evenue Road, Ny 87876",
//     Amount: "$249.7",
//     Payment: "Cash",
//     Contact: "994-51-410-3130",
//   },
// ];

const adminOrders = () => {
  const { t } = useTranslation();
  const [isHiddenModal, setIsHiddenModal] = useState<boolean>(true);
  const { orders, setOrders } = useGlobalStore()


  function changeHidden() {
    setIsHiddenModal((prev) => !prev);
  }

//* GET ORDERS
  const fetchOrders = async () => {
    try {
      const response = await getOrder();
      setOrders(response?.data.result.data);
    } catch (error) {
      console.error("Error can't fetching products:", error);
    }
  };

  console.log("ORDERS ",orders);

  useEffect(() => {
    fetchOrders();
  }, []);

//* DELETE ORDERS
  const deleteOrder = async (id:any) => {
    console.log(id);
    
    const orderObj = {
      order_id: id
    }
    
    const res:any = await deleteOrder(orderObj)
    fetchOrders()
    if(res.status == 204){
      toast.success("Order deleted successfully!")
    };
  }

  return (
    <>
      <Head>
        <title>Admin | Orders</title>
        <meta name="Products" content="Generated by create next app" />
        <link rel="icon" href="/admin-icon.png" />
      </Head>
      <div className=" bg-textBlack min-h-screen px-4">
        <Navbar adminNavbar={true}/>
        
        <ToastContainer/>
        <AdminLeftModal onClickClose={changeHidden} hidden={isHiddenModal} />
        <main className="flex">
          <div className=" hidden sm:block">
            <AdminAside />
          </div>

          <section className=" w-full">
            <div className="m-0 sm:m-5">
              <AdminSecondTitle name="Orders"  p1="Orders" resCategoryARR={""} visibleButton={false} visibleDropwdown={false} buttonInnerText=""/>
            </div>

            <div className="p-5 max-w-full overflow-x-auto">
              <table className=" min-w-full bg-white ">
                <thead className="h-16  text-center text-sm not-italic font-semibold leading-6">
                  <tr>
                    <td>ID</td>
                    <td>{t("adminOrder1")}</td>
                    <td>{t("userDesc6")}</td>
                    <td>{t("userDesc7")}</td>
                    <td>{t("userDesc9")}</td>
                    <td>{t("userDesc8")}</td>
                    <td>{t("userDesc10")}</td>
                  </tr>
                </thead>
                <tbody className="">
                  {orders?.map((data:any) => (
                    <AdminOrdersTable data={data} />
                  ))}
                </tbody>
              </table>
            </div>
          </section>
        </main>
      </div>
    </>
  );
};

export default adminOrders;
