import Head from "next/head";
import React from "react";

import { useTranslation } from "react-i18next";
import { Navbar } from "../../share/components/Navbar";
import { Footer } from "../../share/components/Footer";
import Image from "next/image";
import { UserAside } from "../../share/components/userAside";

const UserProfile = () => {
  const { t, i18n } = useTranslation();
  return (
    <>
      <Head>
        <title>Foody | User Profile</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/mainBurger.svg" />
      </Head>
      <main>
        <Navbar isRegister={true} forAdmin={null} forLogin={null} />

        <section className="m-4 sm:m-8 flex justify-center gap-10">
          <UserAside/>

          <div className="w-full flex  flex-col  sm:px-8 sm:py-10 flex-wrap gap-x-1 gap-y-8 bg-white sm:bg-whiteLight1">
            <h2 className=" font-semibold text-3xl text-grayText2">{t("userDesc")}</h2>

            <input type="file" id="file" accept="image/*"  className=" hidden" />
            <label htmlFor="file"> 
            <div className=" w-full flex  justify-center ">
              <Image
                width={146}
                height={0}
                src={"user-profile-upload.svg"}
                alt="upload"
                className="cursor-pointer"
              />
            </div>
            </label>
        

            <div className=" sm:m-10 flex flex-wrap justify-between gap-4  ">
              <div className="">
                <label>{t("userProfileContact")}</label>
                <br />
                <input
                  className=" w-[286px] sm:w-[444px] overflow-hidden h-14 p-3 rounded  bg-[#F3F4F6]  sm:bg-white"
                  type="text"
                  name="contact"
                  id=""
                  placeholder="+994"
                />
              </div>
              <div className="">
                <label>Email</label>
                <br />
                <input
                  className="w-[286px] sm:w-[444px] overflow-hidden h-14 p-3 rounded bg-[#F3F4F6]  sm:bg-white"
                  type="text"
                  name="contact"
                  id=""
                  placeholder="example@gmail.com"
                />
              </div>
              <div className="">
                <label>{t("userProfileUsarname")}</label>
                <br />
                <input
                  className="w-[286px] sm:w-[444px] overflow-hidden h-14 p-3 rounded bg-[#F3F4F6]  sm:bg-white"
                  type="text"
                  name="contact"
                  id=""
                  placeholder="Example Example"
                />
              </div>
              <div className="">
                <label>{t("userProfileAddress")}</label>
                <br />
                <input
                  className="w-[286px] sm:w-[444px] overflow-hidden h-14 p-3 rounded bg-[#F3F4F6]  sm:bg-white"
                  type="text"
                  name="contact"
                  id=""
                  placeholder="Ataturk 45 Ganclik Baku"
                />
              </div>
              <div className="">
                <label>{t("userProfileFullname")}</label>
                <br />
                <input
                  className="w-[286px] sm:w-[444px] overflow-hidden h-14 p-3 rounded bg-[#F3F4F6]  sm:bg-white"
                  type="text"
                  name="contact"
                  id=""
                  placeholder="exampleexample"
                />
              </div>
              <div className=" flex items-end ">
                <button className=" w-[286px] sm:w-[444px] h-[53px] rounded bg-[#6FCF97] transition-transform transform duration-300 hover:scale-95">
                  {t("userProfileSave")}
                </button>
              </div>
            </div>

            {/*             
            <div className=" flex flex-wrap gap-10 justify-between">
              <div className=" w-full sm:w-3/7 sm:w-3/4 overflow-hidden">
                <label>contact</label>
                <input
                  className="w-full sm:w-3/7 sm:w-3/4 overflow-hidden h-14 p-3 rounded"
                  type="text"
                  name="contact"
                  id=""
                  placeholder="+994"
                />
              </div>{" "}
              <div className=" w-2/5">
                <label>contact</label>
                <input
                  className=" w-full"
                  type="text"
                  name="contact"
                  id=""
                  placeholder="+994"
                />
              </div>{" "}
              <div className=" w-2/5">
                <label>contact</label>
                <input
                  className=" w-full"
                  type="text"
                  name="contact"
                  id=""
                  placeholder="+994"
                />
              </div>
            </div> */}
          </div>
        </section>

        <Footer isTop={false} />
      </main>
    </>
  );
};

export default UserProfile;
