import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { Footer } from "../../share/components/Footer";
import { Navbar } from "../../share/components/Navbar";
import { Table } from "../../share/components/orderTable/index";
import { useTranslation } from "react-i18next";

const User: NextPage = () => {
  const { t, i18n } = useTranslation();

  return (
    <>
      <Head>
        <title>Foody | User Order</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/mainBurger.svg" />
      </Head>

      <main>
        <Navbar isRegister={true} forAdmin={null} forLogin={null} />

        <section className="m-8 flex justify-center gap-10">
          <div className="rounded-md flex flex-col max-h-screen overflow-y-auto gap-8 bg-whiteLight1 w-1/6 p-4">
            <div className="flex items-center gap-4 cursor-pointer hover:bg-mainRedLight transition-all p-2">
              <Image
                width={25}
                height={0}
                src={"profile.svg"}
                alt="profileIcon"
              />
              <p className="font-semibold text-grayText2 text-lg ">
                {t("userDesc")}
              </p>
            </div>

            <div className="flex items-center gap-4 cursor-pointer hover:bg-mainRedLight transition-all p-2">
              <Image
                width={25}
                height={0}
                src={"basketIcon.svg"}
                alt="basketIcon"
              />
              <p className="font-semibold text-grayText2 text-lg ">
                {t("userDesc2")}
              </p>
            </div>

            <div className="flex items-center gap-4 cursor-pointer hover:bg-mainRedLight transition-all p-2">
              <Image width={25} height={0} src={"order.svg"} alt="orderIcon" />
              <p className="font-semibold text-grayText2 text-lg ">
                {t("userDesc3")}
              </p>
            </div>

            <div className="flex items-center gap-4 cursor-pointer hover:bg-mainRedLight transition-all p-2">
              <Image
                width={25}
                height={0}
                src={"checkout.svg"}
                alt="checkoutIcon"
              />
              <p className="font-semibold text-grayText2 text-lg ">
                {t("userDesc4")}
              </p>
            </div>

            <div className="flex items-center gap-4 cursor-pointer hover:bg-mainRedLight transition-all p-2">
              <Image
                width={25}
                height={0}
                src={"logout.svg"}
                alt="logoutIcon"
              />
              <p className="font-semibold text-grayText2 text-lg ">
                {t("userDesc5")}
              </p>
            </div>
          </div>

          <div className="w-full flex  flex-col justify-between px-8 py-10 flex-wrap gap-x-1 gap-y-8 bg-whiteLight1">
            <h2 className=" font-semibold text-3xl text-grayText2">
              {t("userDesc3")}
            </h2>

            {/* TABLE */}
            <Table />
            {/* TABLE END */}

            <div className="flex w-max items-center justify-center gap-2">
              <button className="bg-white rounded-md border-2 border-mainRedLight hover:scale-95">
                <Image
                  width={25}
                  height={0}
                  src={"beforeArrow.svg"}
                  alt="arrow"
                />
              </button>
              <p className="p-1 px-3 bg-white font-medium border-2 text-grayText2 border-mainRedLight rounded-md">
                1
              </p>
              <p className=" text-grayText1 font-medium">03</p>
              <button className="bg-white rounded-md border-2 border-mainRedLight hover:scale-95">
                <Image
                  width={25}
                  height={0}
                  src={"nextArrow.svg"}
                  alt="arrow"
                />
              </button>
            </div>
          </div>
        </section>

        <Footer isTop={false} />
      </main>
    </>
  );
};

export default User;
