import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { Footer } from "../../share/components/Footer";
import { Navbar } from "../../share/components/Navbar";

const User: NextPage = () => {
  return (
    <>
      <Head>
        <title>Foody | User Order</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/mainBurger.svg" />
      </Head>

      <main>
        <Navbar />

        <section className="m-8 flex justify-center gap-10">
          <div className="rounded-md flex flex-col max-h-screen overflow-y-auto gap-8 bg-whiteLight1 w-1/6 p-4">
            <div className="flex items-center gap-4 cursor-pointer hover:bg-mainRedLight transition-all p-2">
              <Image
                width={25}
                height={0}
                src={"profile.svg"}
                alt="profileIcon"
              />
              <p className="font-semibold text-grayText2 text-[20px] ">
                Profile
              </p>
            </div>

            <div className="flex items-center gap-4 cursor-pointer hover:bg-mainRedLight transition-all p-2">
              <Image
                width={25}
                height={0}
                src={"basketIcon.svg"}
                alt="basketIcon"
              />
              <p className="font-semibold text-grayText2 text-[20px] ">
                Your Basket
              </p>
            </div>

            <div className="flex items-center gap-4 cursor-pointer hover:bg-mainRedLight transition-all p-2">
              <Image width={25} height={0} src={".svg"} alt="orderIcon" />
              <p className="font-semibold text-grayText2 text-[20px] ">
                Your Orders
              </p>
            </div>

            <div className="flex items-center gap-4 cursor-pointer hover:bg-mainRedLight transition-all p-2">
              <Image width={25} height={0} src={".svg"} alt="checkoutIcon" />
              <p className="font-semibold text-grayText2 text-[20px] ">
                Checkout
              </p>
            </div>

            <div className="flex items-center gap-4 cursor-pointer hover:bg-mainRedLight transition-all p-2">
              <Image
                width={25}
                height={0}
                src={"logout.svg"}
                alt="logoutIcon"
              />
              <p className="font-semibold text-grayText2 text-[20px] ">
                Logout
              </p>
            </div>
          </div>

          <div className="w-full flex  flex-col justify-between px-8 py-10 flex-wrap gap-x-1 gap-y-8 bg-whiteLight1">
            <h2 className=" font-semibold text-3xl text-grayText2">
              Your Orders
            </h2>

            {/* TABLE */}
            <table className="min-w-full bg-white text-center">
              <thead>
                <tr>
                  <th className="py-2 px-4 border-b border-whiteLight3">ID</th>
                  <th className="py-2 px-4 border-b border-whiteLight3">
                    Time
                  </th>
                  <th className="py-2 px-4 border-b border-whiteLight3">
                    Delivery Address
                  </th>
                  <th className="py-2 px-4 border-b border-whiteLight3">
                    Amount
                  </th>
                  <th className="py-2 px-4 border-b border-whiteLight3">
                    Payment Methods
                  </th>
                  <th className="py-2 px-4 border-b border-whiteLight3">
                    Contact
                  </th>
                </tr>
              </thead>
              <tbody>
                <tr>
                  <td className="py-2 px-4 border-b border-whiteLight3">
                    0001
                  </td>
                  <td className="py-2 px-4 border-b border-whiteLight3">
                    12:30 PM
                  </td>
                  <td className="py-2 px-4 border-b border-whiteLight3 text-start w-60">
                    29 Eve Street, 543 Evenue Road, Ny 87876
                  </td>
                  <td className="py-2 px-4 border-b border-whiteLight3">
                    $50.00
                  </td>
                  <td className="py-2 px-4 border-b border-whiteLight3">
                    Credit Card
                  </td>
                  <td className="py-2 px-4 border-b border-whiteLight3">
                    994-50-111-11-11
                  </td>
                </tr>
                <tr>
                  <td className="py-2 px-4 border-b border-whiteLight3">
                    0002
                  </td>
                  <td className="py-2 px-4 border-b border-whiteLight3">
                    2:45 PM
                  </td>
                  <td className="py-2 px-4 border-b border-whiteLight3 text-start w-60">
                    29 Eve Street, 543 Evenue Road, Ny 87876
                  </td>
                  <td className="py-2 px-4 border-b border-whiteLight3">
                    $75.00
                  </td>
                  <td className="py-2 px-4 border-b border-whiteLight3">
                    PayPal
                  </td>
                  <td className="py-2 px-4 border-b border-whiteLight3">
                    994-50-111-11-11
                  </td>
                </tr>

                <tr>
                  <td className="py-2 px-4 border-b border-whiteLight3">
                    0003
                  </td>
                  <td className="py-2 px-4 border-b border-whiteLight3">
                    5:00 PM
                  </td>
                  <td className="py-2 px-4 border-b border-whiteLight3 text-start w-60">
                    29 Eve Street, 543 Evenue Road, Ny 87876
                  </td>
                  <td className="py-2 px-4 border-b border-whiteLight3">
                    $100.00
                  </td>
                  <td className="py-2 px-4 border-b border-whiteLight3">
                    Cash
                  </td>
                  <td className="py-2 px-4 border-b border-whiteLight3">
                    994-50-111-11-11
                  </td>
                </tr>
              </tbody>
            </table>
            {/* TABLE END */}

            <div className="flex w-max items-center justify-center gap-2">
              <button className="bg-white rounded-md border-2 border-mainRedLight hover:scale-95">
                <Image
                  width={25}
                  height={0}
                  src={"beforeArrow.svg"}
                  alt="arrow"
                />
              </button>
              <p className="p-1 px-3 bg-white font-medium border-2 text-grayText2 border-mainRedLight rounded-md">
                1
              </p>
              <p className=" text-grayText1 font-medium">03</p>
              <button className="bg-white rounded-md border-2 border-mainRedLight hover:scale-95">
                <Image
                  width={25}
                  height={0}
                  src={"nextArrow.svg"}
                  alt="arrow"
                />
              </button>
            </div>
          </div>
        </section>

        <Footer />
      </main>
    </>
  );
};

export default User;
