import type { NextPage } from "next";
import Head from "next/head";
import { Navbar } from "../../share/components/Navbar";
import { Footer } from "../../share/components/Footer";
import { UserAside } from "../../share/components/userAside";
import { Button } from "../../share/components/Button";
import { useTranslation } from "react-i18next";
import { UserCheckoutAside } from "../../share/components/userCheckoutAside";
import { UserCheckoutForm } from "../../share/components/userCheckForm";

const UserCheckout: NextPage = () => {
  const { t, i18n } = useTranslation();

   
    return (
        <>
        <Head>
        <title>Foody | User Checkout</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/mainBurger.svg" />
      </Head>
      
      <main>
        <Navbar isRegister={true} forAdmin={null} forLogin={null} />
      
        <section className="mx-0 sm:m-8 flex flex-col sm:flex-row justify-center gap-4">
            <UserAside/>
            <div className=" w-full sm:w-[55%] flex flex-col px-3 sm:px-8 py-10 flex-wrap gap-0 sm:bg-whiteLight1">
            <h2 className="font-semibold text-3xl text-grayText2">{t("userDesc4")}</h2>
            <UserCheckoutForm/>
            </div>
            <UserCheckoutAside/>
        </section>
      
      
      
        <Footer isTop={false} />
        </main>
      </>
    )
}

export default UserCheckout