import type { NextPage } from "next";
import Head from "next/head";
import { Navbar } from "../../share/components/Navbar";
import { Footer } from "../../share/components/Footer";
import { UserAside } from "../../share/components/userAside";
import { Button } from "../../share/components/Button";
import { useTranslation } from "react-i18next";
import { UserCheckoutAside } from "../../share/components/userCheckoutAside";
import { UserCheckoutForm } from "../../share/components/userCheckForm";

const UserCheckout: NextPage = () => {
  const { t } = useTranslation();
  
   
    return (
        <>
        <Head>
        <title>Foody | User Checkout</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/mainBurger.svg" />
      </Head>
      
      <main>
        <Navbar />
      
        <section className="mx-0 sm:m-8 flex flex-col sm:flex-row justify-center gap-4">
            <UserAside/>
            <UserCheckoutForm/>
        </section>
      
      
      
        <Footer isTop={false} />
        </main>
      </>
    )
}

export default UserCheckout