import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { Header } from "../share/components/Header";
import { Footer } from "../share/components/Footer";
import { useTranslation } from "react-i18next";

const Home: NextPage = () => {
  const { t, i18n } = useTranslation();

  return (
    <>
      <Head>
        <title>Foody | Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/mainBurger.svg" />
      </Head>

      <main>
        <Header />

        {/* FIRST SECTION COMPONENT */}
        <section className="flex flex-col gap-10 justify-center my-14 px-14">
          <div className="flex flex-col gap-6 items-center text-center">
            <h3 className=" text-5xl font-black">{t("homeDesc5")}</h3>
            <p className="w-full sm:w-2/3 text-2xl text-grayText1">
              Lorem ipsum is placeholder text commonly used in the graphic,
              print, and publishing industries for previewing layouts and visual
              mockups.
            </p>
          </div>

          <div className="flex flex-col sm:flex-row justify-center gap-16 items-center">
            <div className="flex flex-col gap-5 text-center pb-6 shadow-xl">
              <Image
                width={240}
                className="mx-auto"
                height={0}
                src={"discountCard.svg"}
                alt="discount"
              />
              <p className=" font-bold text-3xl text-grayText2">
                Discount Boucher
              </p>
              <p className=" w-2/3 mx-auto text-grayText1 text-lg">
                Lorem ipsum is placeholder commonly used in the graphic{" "}
              </p>
            </div>

            <div className="flex flex-col gap-5 text-center pb-6 shadow-xl">
              <Image
                width={240}
                className="mx-auto"
                height={0}
                src={"soupCard.svg"}
                alt="soup"
              />
              <p className=" font-bold text-3xl text-grayText2">
                Fresh healthy Food
              </p>
              <p className=" w-2/3 mx-auto text-grayText1 text-lg">
                Lorem ipsum is placeholder commonly used in the graphic{" "}
              </p>
            </div>

            <div className="flex flex-col gap-5 text-center pb-6 shadow-xl ">
              <Image
                width={210}
                className="mx-auto"
                height={0}
                src={"deliveryCard.svg"}
                alt="delivery"
              />
              <p className=" font-bold text-3xl text-grayText2">
                Fast Home Delivery
              </p>
              <p className=" w-2/3 mx-auto text-grayText1 text-lg">
                Lorem ipsum is placeholder commonly used in the graphic{" "}
              </p>
            </div>
          </div>
        </section>
        {/* FIRST SECTION COMPONENT END */}

        {/* SECOND SECTION COMPONENT */}
        <section className="flex flex-col sm:flex-row justify-center items-center px-11 mt-52">
          <div className="flex flex-col gap-8 w-full sm:w-1/2">
            <h4 className="text-5xl w-3/4 sm:w-full sm:text-6xl font-black leading-tight text-center mx-auto sm:mx-0 sm:text-start">
              {t("homeDesc6")}
            </h4>
            <p className="text-xl text-grayText1 w-full mb-8 sm:mb-0 sm:w-3/5 mx-auto text-center sm:text-start sm:mx-0">
              Lorem ipsum is placeholder text commonly used in the graphic,
              print, and publishing industries for previewing layouts and visual
              mockups.Lorem ipsum is placeholder text commonly used in the
              graphic, print, and publishing industries for previewing layouts
              and visual mockups.
            </p>
          </div>
          <div>
            <Image
              className="w-full"
              width={0}
              height={0}
              src={"mainKfc.svg"}
              alt="kfc"
            />
          </div>
        </section>
        {/* SECOND SECTION COMPONENT END */}

        {/* THIRD SECTION COMPONENT */}
        <section className="flex flex-col sm:flex-row justify-center items-center px-11 mt-52">
          <div className="flex flex-col gap-8 w-full sm:w-1/2">
            <h4 className="text-5xl w-3/4 sm:w-full sm:text-6xl font-black leading-tight text-center mx-auto sm:mx-0 sm:text-start">
              {t("homeDesc7")}
            </h4>
            <p className="text-xl text-grayText1 w-full mb-8 sm:mb-0 sm:w-3/5 mx-auto text-center sm:text-start sm:mx-0">
              Lorem ipsum is placeholder text commonly used in the graphic,
              print, and publishing industries for previewing layouts and visual
              mockups.Lorem ipsum is placeholder text commonly used in the
              graphic, print, and publishing industries for previewing layouts
              and visual mockups.
            </p>
          </div>
          <div>
            <Image
              className="w-full"
              width={0}
              height={0}
              src={"mainPizza.svg"}
              alt="pizza"
            />
          </div>
        </section>
        {/* THIRD SECTION COMPONENT END */}

        {/* FOURTH SECTION COMPONENT */}
        <section className="flex flex-col sm:flex-row justify-center items-center px-11 mt-52">
          <div className="flex flex-col gap-8 w-full sm:w-1/2">
            <h4 className="text-5xl w-3/4 sm:w-full sm:text-6xl font-black leading-tight text-center mx-auto sm:mx-0 sm:text-start">
              {t("homeDesc8")}
            </h4>
            <p className="text-xl text-grayText1 w-full mb-8 sm:mb-0 sm:w-3/5 mx-auto text-center sm:text-start sm:mx-0">
              Lorem ipsum is placeholder text commonly used in the graphic,
              print, and publishing industries for previewing layouts and visual
              mockups.Lorem ipsum is placeholder text commonly used in the
              graphic, print, and publishing industries for previewing layouts
              and visual mockups.
            </p>
          </div>
          <div>
            <Image
              className="w-full"
              width={0}
              height={0}
              src={"mainFries.svg"}
              alt="fries"
            />
          </div>
        </section>
        {/* FOURTH SECTION COMPONENT END */}

        {/* FIFTH SECTION COMPONENT */}
        <section className="flex flex-col gap-10 justify-center px-14 mb-96">
          <div className="flex flex-col gap-6 items-center text-center">
            <h3 className=" text-5xl font-black w-full mt-20 sm:mt-0 sm:w-1/3 leading-tight">
              {t("homeDesc9")}
            </h3>
            <p className="w-full sm:w-2/3 text-2xl text-grayText1">
              Lorem ipsum is placeholder text commonly used in the graphic,
              print, and publishing industries for previewing layouts and visual
              mockups.
            </p>
          </div>

          <div className="flex flex-col sm:flex-row justify-center gap-16 items-center">
            <div className="flex flex-col gap-5 text-center pb-6 shadow-xl ">
              <Image
                width={240}
                className="mx-auto"
                height={0}
                src={"burgerAnimation.svg"}
                alt="burger"
              />
              <p className=" font-bold text-3xl text-grayText2">Dubble Chees</p>
              <p className=" w-2/3 mx-auto text-grayText1 text-lg">
                Lorem ipsum is placeholder commonly used in the graphic{" "}
              </p>
            </div>

            <div className="flex flex-col gap-5 text-center pb-6 shadow-xl ">
              <Image
                width={190}
                className="mx-auto"
                height={0}
                src={"margaritaCard.svg"}
                alt="margarita"
              />
              <p className=" font-bold text-3xl text-grayText2">Margarita</p>
              <p className=" w-2/3 mx-auto text-grayText1 text-lg">
                Lorem ipsum is placeholder commonly used in the graphic{" "}
              </p>
            </div>

            <div className="flex flex-col gap-5 text-center pb-6 shadow-xl ">
              <Image
                width={240}
                className="mx-auto"
                height={0}
                src={"kfcCard.svg"}
                alt="kfc"
              />
              <p className=" font-bold text-3xl text-grayText2">Twister Menu</p>
              <p className=" w-2/3 mx-auto text-grayText1 text-lg">
                Lorem ipsum is placeholder commonly used in the graphic{" "}
              </p>
            </div>
          </div>
        </section>
        {/* FIFTH SECTION COMPONENT END */}

        <Footer isTop={true} />
      </main>
    </>
  );
};

export default Home;
