import { Navbar } from "@/share/components/Navbar";
import { AdminAside } from "@/share/components/adminAside";
import AdminOrderHistoryTable from "@/share/components/adminOrderHistoryTable";
import AdminSecondTitle from "@/share/components/adminSecondTitle";
import { getHistory } from "@/share/services/axios";
import { useGlobalStore } from "@/share/services/provider";
import Head from "next/head";
import React, { useEffect } from "react";
import { useTranslation } from "react-i18next";

const adminOrdersHistory = () => {
  const { t } = useTranslation();
  const { history, setHistory} = useGlobalStore()

  //* GET HISTORY


  const renderOrders = async () => {
    const res = await getHistory()
    setHistory(res?.data.result.data)
  }

  useEffect(() => {
    renderOrders()
  },[])

  return (
    <>
      <Head>
        <title>Admin | History</title>
        <meta name="Products" content="Generated by create next app" />
        <link rel="icon" href="/admin-icon.png" />
      </Head>
      <div className=" bg-textBlack min-h-screen px-4">
        <Navbar adminNavbar={true}/>


        <main className="flex">
          <div className=" hidden sm:block">
            <AdminAside />
          </div>


          <section className=" w-full">
            <div className="m-0 sm:m-5">
              <AdminSecondTitle name="History"  p1="History" resCategoryARR={""} visibleButton={false} visibleDropwdown={false} buttonInnerText=""/>
            </div>

            <div className="p-5 max-h-[500px] overflow-y-auto">
              <table className="w-full bg-white">
                <thead className="h-16 text-center text-sm not-italic font-semibold leading-6">
                <tr>
                    <td>ID</td>
                    <td>{t("adminOrder1")}</td>
                    <td>{t("userDesc6")}</td>
                    <td>{t("userDesc7")}</td>
                    <td>{t("userDesc9")}</td>
                    <td>{t("userDesc8")}</td>
                    <td>{t("userDesc10")}</td>
                  </tr>
                </thead>
                <tbody className="">
                  {history?.map((data:any) => (
                    <AdminOrderHistoryTable data={data} />
                  ))}
                </tbody>
              </table>
            </div>
          </section>
        </main>
      </div>
    </>
  );
};

export default adminOrdersHistory;
