import { Navbar } from "@/share/components/Navbar";
import { AdminAside } from "@/share/components/adminAside";
import AdminOrderHistoryTable from "@/share/components/adminOrderHistoryTable";
import AdminSecondTitle from "@/share/components/adminSecondTitle";
import { getOrderHistory } from "@/share/services/axios";
import Head from "next/head";
import React, { useEffect, useState } from "react";

const item = [
  {
    id: 9177,
    customerId: 22401,
    Time: "25 Dec 2021",
    Address: "29 Eve Street, 543 Evenue Road, Ny 87876",
    Amount: "$249.7",
    Payment: "Cash",
    Contact: "994-51-410-3130",
  },
  {
    id: 9178,
    customerId: 22401,
    Time: "25 Dec 2021",
    Address: "29 Eve Street, 543 Evenue Road, Ny 87876",
    Amount: "$249.7",
    Payment: "Cash",
    Contact: "994-51-410-3130",
  },
  {
    id: 9179,
    customerId: 22401,
    Time: "25 Dec 2021",
    Address: "29 Eve Street, 543 Evenue Road, Ny 87876",
    Amount: "$249.7",
    Payment: "Cash",
    Contact: "994-51-410-3130",
  },
  {
    id: 9200,
    customerId: 22401,
    Time: "25 Dec 2021",
    Address: "29 Eve Street, 543 Evenue Road, Ny 87876",
    Amount: "$249.7",
    Payment: "Cash",
    Contact: "994-51-410-3130",
  },
];

const adminOrdersHistory = () => {

const [history,setHistory] = useState()

  
 async function renderHistory() {
   const res: any = await getOrderHistory()
   setHistory(res)
  }
  useEffect(() => {
    renderHistory()
    console.log(history);
    
  })

  return (
    <>
      <Head>
        <title>admin</title>
        <meta name="Products" content="Generated by create next app" />
        <link rel="icon" href="/admin-icon.png" />
      </Head>
      <div className=" bg-textBlack min-h-screen px-4">
        <Navbar adminNavbar={true}/>


        <main className="flex">
          <div className=" hidden sm:block">
            <AdminAside />
          </div>


          <section className=" w-full">
            <div className="m-5">
              <AdminSecondTitle name="History"  p1="History" />
            </div>

            {/* <div className=" w-full sm:w-auto m-5 flex flex-wrap gap-4 justify-center">
              {item.map((data) => (
                <AdminRestouransCard data={data} />
              ))}
            </div> */}
            <div className="p-5">
              <table className=" w-full bg-white ">
                <thead className="h-16  text-center text-sm not-italic font-semibold leading-6">
                <tr>
                    <td>ID</td>
                    <td>Customer ID</td>
                    <td>Time</td>
                    <td>Delivery Address</td>
                    <td>Amount</td>
                    <td>Payment Method</td>
                    <td>Contact</td>
                    <td></td>
                  </tr>
                </thead>
                <tbody className="">
                  {item.map((data) => (
                    // <AdminOrdersTable data={data} />
                    <AdminOrderHistoryTable data={data} />
                  ))}
                </tbody>
              </table>
            </div>
          </section>
        </main>
      </div>
    </>
  );
};

export default adminOrdersHistory;
