import type { NextPage } from "next";
import Head from "next/head";
import { AdminHeader } from "../../../share/components/adminHeader";
import { AdminAside } from "../../../share/components/adminAside";
import { AdminLeftModal } from "../../../share/components/adminLeftModal";
import { useRef, useState } from "react";
import AdminCategory from "../../../share/components/adminCategory";
import AdminSecondTitle from "../../../share/components/adminSecondTitle";
import { UpperCase } from "@/share/services/upperCase";
import { url } from "inspector";
import { Form, postCategory } from "@/share/services/axios";

interface CategoryType {
  id: number;
  image: string;
  name: string;
  slug: string;
}

const AdminProducts: NextPage = () => {
  const categoryRef = useRef<React.RefObject<HTMLInputElement> | null>() 
  const slugRef=useRef <React.RefObject<HTMLInputElement>|null>() 
  const [imgUrl, setImgUrl] = useState<string>("")
  
  function getImgUrl(url:string):void {
    //  console.log(url);
    setImgUrl(url)
   
  }
  async function  addCategory() {

    const value = categoryRef?.current?.value

    const slug = slugRef?.current?.value
    
    const img = imgUrl

    const form:Form= {
      "name": value,
      "slug":slug ,
      "img_url": img
    }
    const res = await postCategory(form)
    console.log(res);
    
    // console.log(UpperCase(value));

 
  }
  

  const [isHiddenModal, setIsHiddenModal] = useState<boolean>(true);
  function changeHidden(): void {
    setIsHiddenModal((prev: boolean) => !prev);
    console.log(isHiddenModal);
  }
  let categoryData: CategoryType[] = [
    {
      id: 2000,
      image: "/adminMarqarita.svg",
      name: "pizza",
      slug: "Yummy-pizza",
    },
    {
      id: 2001,
      image: "/adminMarqarita.svg",
      name: "hotdog",
      slug: "Yummy-pizza",
    },
    {
      id: 2002,
      image: "/adminMarqarita.svg",
      name: "pizza",
      slug: "Yummy-pizza",
    },
    {
      id: 2003,
      image: "/adminMarqarita.svg",
      name: "pizza",
      slug: "Yummy-pizza",
    },
  ];
  // console.log("categoryData", categoryData);

  return (
    <>
      <Head>
        <title>admin</title>
        <meta name="Products" content="Generated by create next app" />
        <link rel="icon" href="/admin-icon.png" />
      </Head>

      <div className=" bg-textBlack min-h-screen px-4">
        <AdminHeader />

        <main className="flex">
          <div className=" hidden sm:block">
            <AdminAside />
          </div>

          <section className=" w-[100%] m-5">
            <AdminLeftModal
              onClickClose={changeHidden}
              mod="3"
              p="Add Category  "
              p1="Upload  image"
              p2="Add your Category information"
              hidden={isHiddenModal}
              btn="Create Category"
              categoryRef={categoryRef}
              ButtonOnClick={addCategory}
              getImgUrl={getImgUrl}
              slugRef={slugRef}
            />
            {/* <div className=" flex  justify-between text-sm  font-semibold h-16 items-center px-8"></div> */}
            <AdminSecondTitle onClick={changeHidden} name="Catagory" p1="Catagory" />
            <div className=" w-[100%]   bg-white">
              <table className="w-[100%] ">
                <thead className="h-16 text-sm px-8">
                  <tr>
                    <th>ID</th>
                    <th>Image</th>
                    <th>Name</th>
                    <th>Slug</th>
                    <th>Edit and delete</th>
                  </tr>
                </thead>

                <tbody>
                  {categoryData.map((item: CategoryType) => (
                    <AdminCategory key={item.id} item={item} />
                  ))}
                </tbody>
              </table>
            </div>
          </section>
        </main>
      </div>
    </>
  );
};

export default AdminProducts;
