import type { NextPage } from "next";
import Head from "next/head";
import { AdminHeader } from "../../../share/components/adminHeader";
import { AdminAside } from "../../../share/components/adminAside";
import OrdersChart from "../../../share/components/ordersChart";
import Barchart from "../../../share/components/LineChart";
import { AdminLeftModal } from "../../../share/components/adminLeftModal";
import { useState } from "react";
import AdminCard from "../../../share/components/adminCard";
import AdminCategory from "../../../share/components/adminCategory";
import AdminSecondTitle from "../../../share/components/adminSecondTitle";
import Modal from "../../../share/components/Modal";
import { Button } from "../../../share/components/Button";
import { useTranslation } from "react-i18next";

interface CategoryType {
  id: number;
  image: string;
  name: string;
  slug: string;
}

const AdminProducts: NextPage = () => {
  const [isHiddenModal, setIsHiddenModal] = useState<boolean>(true);
  function changeHidden(): void {
    setIsHiddenModal((prev: boolean) => !prev);
    console.log(isHiddenModal);
  }
  let categoryData: CategoryType[] = [
    {
      id: 2000,
      image: "/adminMarqarita.svg",
      name: "pizza",
      slug: "Yummy-pizza",
    },
    {
      id: 2001,
      image: "/adminMarqarita.svg",
      name: "hotdog",
      slug: "Yummy-pizza",
    },
    {
      id: 2002,
      image: "/adminMarqarita.svg",
      name: "pizza",
      slug: "Yummy-pizza",
    },
    {
      id: 2003,
      image: "/adminMarqarita.svg",
      name: "pizza",
      slug: "Yummy-pizza",
    },
  ];
  console.log("categoryData", categoryData);

  return (
    <>
      <Head>
        <title>admin</title>
        <meta name="Products" content="Generated by create next app" />
        <link rel="icon" href="/admin-icon.png" />
      </Head>

      <div className=" bg-textBlack min-h-screen px-4">
        <AdminHeader onClickButton={changeHidden} />

        <AdminLeftModal onClickClose={changeHidden} hidden={isHiddenModal} />
        <main className="flex">
          <div className=" hidden sm:block">
            <AdminAside />
          </div>

          <div className=" gap-4 hidden">
            <OrdersChart />
            <Barchart />
          </div>
          <section className=" w-[100%] m-5">
            {/* <div className=" flex  justify-between text-sm  font-semibold h-16 items-center px-8"></div> */}
            <AdminSecondTitle name="Catagory" />
            <div className=" w-[100%]   bg-white">
              <table className="w-[100%] ">
                <thead className="h-16 text-sm px-8">
                  <tr>
                    <th>ID</th>
                    <th>Image</th>
                    <th>Name</th>
                    <th>Slug</th>
                    <th>Edit and delete</th>
                  </tr>
                </thead>

                <tbody>
                  {categoryData.map((item: CategoryType) => (
                    <AdminCategory key={item.id} item={item} />
                  ))}
                </tbody>
              </table>
            </div>
          </section>
        </main>
       
      </div>
    </>
  );
};

export default AdminProducts;
